### ISSUE TITLE
Add encoder implementation

### ISSUE THREAD

**Issue by Piasy** [joffrey-bion/socketio-kotlin#95]
Hi Joffrey, I'm exploring KMP SocketIO implementations, and find [dyte-io/socketio-kotlin](https://github.com/dyte-io/socketio-kotlin), which uses your source code, so I find your great repo.

I'm just wondering if it's possible to add encoder implementation here.

**Comment by joffrey-bion** [comment]
Hi! Thanks for letting me know. Indeed it would be nice and relatively easy to add the encoding side as well. I just wrote the decoding side initially because I just needed that personally.

**Comment by Piasy** [comment]
okay, I'll try to add encoding support and submit PR later.

Best regards.
Piasy Xu

此致，祝好！
许建林

<https://github.com/Piasy>
<https://www.linkedin.com/in/piasy/>

**Comment by joffrey-bion** [comment]
I'm already working on it, don't bother ;)

**Comment by Piasy** [comment]
Hi  Joffrey, could you please publish a new release to maven central?

Best regards.
Piasy Xu

此致，祝好！
许建林

<https://github.com/Piasy>
<https://www.linkedin.com/in/piasy/>

**Comment by joffrey-bion** [comment]
I published one yesterday, you should see 1.6.0. isn't it the case? (The badge on the readme doesn't seem to work, so please try to use 1.6.0 in Gradle or maven).

I'm afk for now, but if you can't use 1.6.0 let me know and I'll have a look at the publication.

**Comment by Piasy** [comment]
<img width="790" alt="Screenshot 2024-12-25 at 23 33 23" src="https://github.com/user-attachments/assets/7a001486-f3c2-4481-a5d7-0ae4fa4d454b" />

Latest version on maven central is 1.4.0, also depending on 1.6.0 fails with unresolved artifact.

**Comment by joffrey-bion** [comment]
For some reason the repository from sonatype automatically. I manually triggered it, you should have access now

**Comment by joffrey-bion** [comment]
Cool! I'm happy to see that my lib was useful to you :)
